# https://github.com/sandhose/nixconf/blob/master/.github/workflows/update.yaml
name: "build flake"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: tibdex/github-app-token@v1.5
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: cachix/install-nix-action@v16
        with:
          install_url: https://releases.nixos.org/nix/nix-2.6.1/install
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: build
        run: nix build
      - name: Archive result artifact
        uses: actions/upload-artifact@v3
        with:
          name: result
          path: |
            result
